In [ ]:
#########################################################################
##BASE Level Model for Machine Learning with imputing and Normalization
#########################################################################

In [1]:
import numpy as np
import pandas as pd  
import matplotlib.pyplot as plt   
import seaborn as sns
%matplotlib inline 

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [45]:
baseClass = pd.read_csv("C:\\Users\\Vinit Thakur\\Desktop\\BaseExample.csv") 

In [46]:
baseClass=base.dropna(subset=['smoke'])

In [47]:
baseClass.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1997 entries, 0 to 1999
Data columns (total 12 columns):
sex         1997 non-null object
age         1997 non-null int64
edu         1997 non-null object
unempdur    1380 non-null float64
income      1492 non-null float64
marital     1995 non-null object
sport       1981 non-null object
smoke       1997 non-null object
alcabuse    1995 non-null object
workab      1818 non-null object
englang     1993 non-null object
bmi         1968 non-null float64
dtypes: float64(3), int64(1), object(8)
memory usage: 202.8+ KB


In [48]:
baseClass['marital'].fillna(baseClass['marital'].mode()[0], inplace=True)
baseClass['alcabuse'].fillna(baseClass['alcabuse'].mode()[0], inplace=True)
baseClass['workab'].fillna(baseClass['workab'].mode()[0], inplace=True)
baseClass['englang'].fillna(baseClass['englang'].mode()[0], inplace=True)
baseClass['sport'].fillna(baseClass['sport'].mode()[0], inplace=True)
baseClass['unempdur'].fillna(baseClass['unempdur'].mean(), inplace=True)
baseClass['bmi'].fillna(baseClass['bmi'].mean(), inplace=True)
baseClass['income'].fillna(baseClass['income'].mean(), inplace=True)

In [50]:
x = baseClass.drop(columns=['smoke'])
y = baseClass['smoke']

In [51]:
x = pd.get_dummies(x, prefix_sep='_', drop_first=True)

In [52]:
# Split X and y into training and test set in 70:30 ratio
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.30, random_state=1)

In [53]:
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics

In [72]:
# Invoking the NB Gaussian function to create the model
# fitting the model in the training data set
model = GaussianNB()
model.fit(x_train, y_train)
y_predict = model.predict(x_test)
model_score = model.score(x_test, y_test)
print(model_score)
print(metrics.confusion_matrix(y_test, y_predict))

0.7016666666666667
[[393  39]
 [140  28]]


In [56]:
from sklearn.linear_model import LogisticRegression

In [57]:
model = LogisticRegression()
model.fit(x_train, y_train)
y_predict = model.predict(x_test)
model_score = model.score(x_test, y_test)
print(model_score)
print(metrics.confusion_matrix(y_test, y_predict))

0.72
[[416  16]
 [152  16]]


In [58]:
from sklearn import tree


clf = tree.DecisionTreeClassifier()
clf = clf.fit(x_train, y_train)

In [59]:
y_predict = clf.predict(x_test)
model_score = clf.score(x_test, y_test)
print(model_score)
print(metrics.confusion_matrix(y_test, y_predict))

0.7
[[343  89]
 [ 91  77]]


In [63]:
#Import Random Forest Model
from sklearn.ensemble import RandomForestClassifier

#Create a Gaussian Classifier
clfRF=RandomForestClassifier(n_estimators=100)

#Train the model using the training sets y_pred=clf.predict(X_test)
clfRF.fit(x_train,y_train)

y_pred=clfRF.predict(x_test)
model_scoreRF = clfRF.score(x_test, y_test)

In [64]:
print(model_scoreRF)
print(metrics.confusion_matrix(y_test, y_pred))

0.7466666666666667
[[401  31]
 [121  47]]


In [65]:
from sklearn import svm

clfSVM = svm.SVC()
clfSVM.fit(x_train, y_train)
y_pred=clfSVM.predict(x_test)
model_scoreSVM = clfSVM.score(x_test, y_test)
print(model_scoreSVM)
print(metrics.confusion_matrix(y_test, y_pred))


0.7183333333333334
[[418  14]
 [155  13]]


In [68]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
clfLDA = LinearDiscriminantAnalysis()
clfLDA.fit(x_train, y_train)
y_pred=clfLDA.predict(x_test)
model_scoreLDA = clfLDA.score(x_test, y_test)
print(model_scoreLDA)
print(metrics.confusion_matrix(y_test, y_pred))

0.7183333333333334
[[415  17]
 [152  16]]


In [69]:
from sklearn.ensemble import AdaBoostClassifier


clfADB = AdaBoostClassifier(n_estimators=100)
clfADB.fit(x_train,y_train)
y_pred=clfADB.predict(x_test)
model_scoreADB = clfADB.score(x_test, y_test)
print(model_scoreADB)
print(metrics.confusion_matrix(y_test, y_pred))

0.75
[[405  27]
 [123  45]]


In [70]:
from sklearn.neighbors import KNeighborsClassifier

clfKNN=KNeighborsClassifier()
clfKNN.fit(x_train,y_train)
y_pred=clfKNN.predict(x_test)
model_scoreKNN = clfKNN.score(x_test, y_test)
print(model_scoreKNN)
print(metrics.confusion_matrix(y_test, y_pred))

0.71
[[387  45]
 [129  39]]


In [71]:
import xgboost as xgb
clfXGB=xgb.XGBClassifier(random_state=1,learning_rate=0.01)
clfXGB.fit(x_train, y_train)
y_pred=clfXGB.predict(x_test)
model_scoreXGB=clfXGB.score(x_test,y_test)
print(model_scoreXGB)
print(metrics.confusion_matrix(y_test,y_pred))

0.715
[[413  19]
 [152  16]]


In [74]:
from sklearn.model_selection import cross_val_score
clfCVRF = RandomForestClassifier(n_estimators=100)
scores = cross_val_score(clfCVRF, x_train, y_train, cv=10)
scores


array([0.77142857, 0.76428571, 0.77857143, 0.75714286, 0.76428571,
       0.77857143, 0.73571429, 0.75714286, 0.79136691, 0.7173913 ])